-- Fresh-install schema equivalent to V21, with required system boards seeded.
-- Flyway uses this only for new databases. Existing V1-V21 checksums stay unchanged.
create table app_users (
  id varchar(255) primary key,
  username varchar(255) not null unique,
  email varchar(320),
  role varchar(32) not null check (role in ('ADMIN', 'USER')),
  display_name varchar(255) not null,
  password_hash varchar(100)
);
create unique index uq_app_users_username_ci on app_users ((lower(username)));
create unique index uq_app_users_email_ci on app_users ((lower(email))) where email is not null;

create table boards (
  id varchar(255) primary key,
  name varchar(255) not null,
  headline varchar(255) not null,
  version bigint default 0,
  board_url varchar(255) not null,
  board_name varchar(255) not null,
  owner_user_id varchar(255) not null references app_users(id),
  updated_at timestamp with time zone not null default now()
);
create unique index uq_boards_board_url on boards(board_url);
create index idx_boards_owner_user_id on boards(owner_user_id);

create table if not exists cards (
  pk bigint generated by default as identity primary key,
  id varchar(255) not null,
  label varchar(255) not null,
  href varchar(2048) not null,
  board_id varchar(255) not null,
  position integer,
  constraint fk_cards_board
    foreign key (board_id) references boards(id) on delete cascade
);

create table if not exists widgets (
  id bigint generated by default as identity primary key,
  board_id varchar(255) not null,
  type varchar(255) not null,
  title varchar(255) not null,
  layout varchar(255) not null,
  config_json varchar(4000) not null,
  enabled boolean not null,
  sort_order integer not null,
  constraint fk_widgets_board
    foreign key (board_id) references boards(id) on delete cascade
);

create table if not exists click_events (
  id bigint generated by default as identity primary key,
  board_id varchar(255) not null,
  card_id varchar(255) not null,
  occurred_at timestamp with time zone not null,
  source_ip varchar(255) not null
);

create table if not exists view_events (
  id bigint generated by default as identity primary key,
  board_id varchar(255) not null,
  occurred_at timestamp with time zone not null,
  source_ip varchar(255) not null,
  source varchar(255) not null,
  device_type varchar(255) not null
);

create index if not exists idx_cards_board_id on cards(board_id);
create index if not exists idx_widgets_board_sort on widgets(board_id, sort_order);
create index if not exists idx_click_events_board on click_events(board_id);
create index if not exists idx_click_events_board_card on click_events(board_id, card_id);
create index if not exists idx_click_events_board_occurred on click_events(board_id, occurred_at);
create index if not exists idx_view_events_board on view_events(board_id);
create index if not exists idx_view_events_board_occurred on view_events(board_id, occurred_at);


create table user_preferences (
  user_id varchar(255) primary key references app_users(id) on delete cascade,
  main_board_id varchar(255) references boards(id) on delete set null
);
create index idx_user_preferences_main_board_id on user_preferences(main_board_id);

create table system_settings (
  id smallint primary key check (id = 1),
  global_homepage_board_id varchar(255) not null references boards(id),
  global_insights_board_id varchar(255) not null references boards(id),
  global_settings_board_id varchar(255) not null references boards(id),
  global_signin_board_id varchar(255) not null references boards(id),
  -- Retained at the V21 boundary; V22 removes this obsolete column for all installations.
  global_signup_board_id varchar(255) not null references boards(id),
  updated_at timestamp with time zone not null default now()
);

create table auth_sessions (
  id varchar(64) primary key,
  user_id varchar(64) not null references app_users(id) on delete cascade,
  token_hash char(64) not null unique,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  revoked_at timestamp with time zone
);
create index idx_auth_sessions_user_id on auth_sessions(user_id);
create index idx_auth_sessions_expires_at on auth_sessions(expires_at);

-- The system owner has no password and cannot sign in with password authentication.
insert into app_users (id, username, display_name, email, role)
values ('anvu', 'anvu', 'An Vu', 'anvu@local', 'ADMIN');

insert into boards (id, board_name, board_url, name, headline, owner_user_id)
values
  ('default', 'Default', 'default', 'Welcome', 'Your first board', 'anvu'),
  ('home', 'Home', 'home', 'B26', 'Create a board of your own', 'anvu'),
  ('insights', 'Insights', 'insights', 'Insights', 'Overview of your profile performance', 'anvu'),
  ('settings', 'Settings', 'settings', 'Settings', 'Manage your account and app configuration', 'anvu'),
  ('signin', 'Sign In', 'signin-board', 'Sign In', 'Sign in to manage your board', 'anvu');

insert into user_preferences (user_id, main_board_id) values ('anvu', 'default');
insert into widgets (board_id, type, title, layout, config_json, enabled, sort_order)
values
  ('signin', 'signin', 'Welcome Back!', 'span-2', '{}', true, 0),
  ('settings', 'user-settings', 'User Settings', 'span-4', '{}', true, 0),
  ('settings', 'admin-settings', 'Admin Settings', 'span-4', '{}', true, 1);
